package dao;

import entity.OrderItem;
import entity.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int deleteByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderIId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    OrderItem selectByPrimaryKey(String orderIId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderItem record);
}