package entity;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMBER_ID
     *
     * @mbg.generated
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.ACCOUNT_ID
     *
     * @mbg.generated
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.FIRST_NAME
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.LAST_NAME
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.B_DATE
     *
     * @mbg.generated
     */
    private Date bDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.PHOTO
     *
     * @mbg.generated
     */
    private String photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated
     */
    public Member(String memberId, String accountId, String firstName, String lastName, Date bDate, String phone, String address, String photo) {
        this.memberId = memberId;
        this.accountId = accountId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.bDate = bDate;
        this.phone = phone;
        this.address = address;
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated
     */
    public Member() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMBER_ID
     *
     * @return the value of MEMBER.MEMBER_ID
     *
     * @mbg.generated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMBER_ID
     *
     * @param memberId the value for MEMBER.MEMBER_ID
     *
     * @mbg.generated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.ACCOUNT_ID
     *
     * @return the value of MEMBER.ACCOUNT_ID
     *
     * @mbg.generated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.ACCOUNT_ID
     *
     * @param accountId the value for MEMBER.ACCOUNT_ID
     *
     * @mbg.generated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.FIRST_NAME
     *
     * @return the value of MEMBER.FIRST_NAME
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.FIRST_NAME
     *
     * @param firstName the value for MEMBER.FIRST_NAME
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.LAST_NAME
     *
     * @return the value of MEMBER.LAST_NAME
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.LAST_NAME
     *
     * @param lastName the value for MEMBER.LAST_NAME
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.B_DATE
     *
     * @return the value of MEMBER.B_DATE
     *
     * @mbg.generated
     */
    public Date getbDate() {
        return bDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.B_DATE
     *
     * @param bDate the value for MEMBER.B_DATE
     *
     * @mbg.generated
     */
    public void setbDate(Date bDate) {
        this.bDate = bDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.PHONE
     *
     * @return the value of MEMBER.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.PHONE
     *
     * @param phone the value for MEMBER.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.ADDRESS
     *
     * @return the value of MEMBER.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.ADDRESS
     *
     * @param address the value for MEMBER.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.PHOTO
     *
     * @return the value of MEMBER.PHOTO
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.PHOTO
     *
     * @param photo the value for MEMBER.PHOTO
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }
}