package entity;

import java.util.ArrayList;
import java.util.List;

public class OrderItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public OrderItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIIdIsNull() {
            addCriterion("ORDER_I_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderIIdIsNotNull() {
            addCriterion("ORDER_I_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIIdEqualTo(String value) {
            addCriterion("ORDER_I_ID =", value, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdNotEqualTo(String value) {
            addCriterion("ORDER_I_ID <>", value, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdGreaterThan(String value) {
            addCriterion("ORDER_I_ID >", value, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_I_ID >=", value, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdLessThan(String value) {
            addCriterion("ORDER_I_ID <", value, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdLessThanOrEqualTo(String value) {
            addCriterion("ORDER_I_ID <=", value, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdLike(String value) {
            addCriterion("ORDER_I_ID like", value, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdNotLike(String value) {
            addCriterion("ORDER_I_ID not like", value, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdIn(List<String> values) {
            addCriterion("ORDER_I_ID in", values, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdNotIn(List<String> values) {
            addCriterion("ORDER_I_ID not in", values, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdBetween(String value1, String value2) {
            addCriterion("ORDER_I_ID between", value1, value2, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIIdNotBetween(String value1, String value2) {
            addCriterion("ORDER_I_ID not between", value1, value2, "orderIId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("ORDER_ID =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("ORDER_ID <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("ORDER_ID >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_ID >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("ORDER_ID <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("ORDER_ID <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("ORDER_ID like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("ORDER_ID not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("ORDER_ID in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("ORDER_ID not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("ORDER_ID between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("ORDER_ID not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("PRODUCT_ID is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("PRODUCT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("PRODUCT_ID =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("PRODUCT_ID <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("PRODUCT_ID >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_ID >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("PRODUCT_ID <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_ID <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("PRODUCT_ID like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("PRODUCT_ID not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("PRODUCT_ID in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("PRODUCT_ID not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("PRODUCT_ID between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_ID not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andOiAmountIsNull() {
            addCriterion("OI_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andOiAmountIsNotNull() {
            addCriterion("OI_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andOiAmountEqualTo(Integer value) {
            addCriterion("OI_AMOUNT =", value, "oiAmount");
            return (Criteria) this;
        }

        public Criteria andOiAmountNotEqualTo(Integer value) {
            addCriterion("OI_AMOUNT <>", value, "oiAmount");
            return (Criteria) this;
        }

        public Criteria andOiAmountGreaterThan(Integer value) {
            addCriterion("OI_AMOUNT >", value, "oiAmount");
            return (Criteria) this;
        }

        public Criteria andOiAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("OI_AMOUNT >=", value, "oiAmount");
            return (Criteria) this;
        }

        public Criteria andOiAmountLessThan(Integer value) {
            addCriterion("OI_AMOUNT <", value, "oiAmount");
            return (Criteria) this;
        }

        public Criteria andOiAmountLessThanOrEqualTo(Integer value) {
            addCriterion("OI_AMOUNT <=", value, "oiAmount");
            return (Criteria) this;
        }

        public Criteria andOiAmountIn(List<Integer> values) {
            addCriterion("OI_AMOUNT in", values, "oiAmount");
            return (Criteria) this;
        }

        public Criteria andOiAmountNotIn(List<Integer> values) {
            addCriterion("OI_AMOUNT not in", values, "oiAmount");
            return (Criteria) this;
        }

        public Criteria andOiAmountBetween(Integer value1, Integer value2) {
            addCriterion("OI_AMOUNT between", value1, value2, "oiAmount");
            return (Criteria) this;
        }

        public Criteria andOiAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("OI_AMOUNT not between", value1, value2, "oiAmount");
            return (Criteria) this;
        }

        public Criteria andOiPriceIsNull() {
            addCriterion("OI_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andOiPriceIsNotNull() {
            addCriterion("OI_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andOiPriceEqualTo(Boolean value) {
            addCriterion("OI_PRICE =", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceNotEqualTo(Boolean value) {
            addCriterion("OI_PRICE <>", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceGreaterThan(Boolean value) {
            addCriterion("OI_PRICE >", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceGreaterThanOrEqualTo(Boolean value) {
            addCriterion("OI_PRICE >=", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceLessThan(Boolean value) {
            addCriterion("OI_PRICE <", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceLessThanOrEqualTo(Boolean value) {
            addCriterion("OI_PRICE <=", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceIn(List<Boolean> values) {
            addCriterion("OI_PRICE in", values, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceNotIn(List<Boolean> values) {
            addCriterion("OI_PRICE not in", values, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceBetween(Boolean value1, Boolean value2) {
            addCriterion("OI_PRICE between", value1, value2, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceNotBetween(Boolean value1, Boolean value2) {
            addCriterion("OI_PRICE not between", value1, value2, "oiPrice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}