package entity;

import java.util.Date;

public class OrderList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_LIST.ORDER_ID
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_LIST.ACCOUNT_ID
     *
     * @mbg.generated
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_LIST.O_DATE
     *
     * @mbg.generated
     */
    private Date oDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_LIST.O_TOTAL_PRICE
     *
     * @mbg.generated
     */
    private Integer oTotalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_LIST.O_RETURN
     *
     * @mbg.generated
     */
    private Boolean oReturn;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbg.generated
     */
    public OrderList(String orderId, String accountId, Date oDate, Integer oTotalPrice, Boolean oReturn) {
        this.orderId = orderId;
        this.accountId = accountId;
        this.oDate = oDate;
        this.oTotalPrice = oTotalPrice;
        this.oReturn = oReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbg.generated
     */
    public OrderList() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_LIST.ORDER_ID
     *
     * @return the value of ORDER_LIST.ORDER_ID
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_LIST.ORDER_ID
     *
     * @param orderId the value for ORDER_LIST.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_LIST.ACCOUNT_ID
     *
     * @return the value of ORDER_LIST.ACCOUNT_ID
     *
     * @mbg.generated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_LIST.ACCOUNT_ID
     *
     * @param accountId the value for ORDER_LIST.ACCOUNT_ID
     *
     * @mbg.generated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_LIST.O_DATE
     *
     * @return the value of ORDER_LIST.O_DATE
     *
     * @mbg.generated
     */
    public Date getoDate() {
        return oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_LIST.O_DATE
     *
     * @param oDate the value for ORDER_LIST.O_DATE
     *
     * @mbg.generated
     */
    public void setoDate(Date oDate) {
        this.oDate = oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_LIST.O_TOTAL_PRICE
     *
     * @return the value of ORDER_LIST.O_TOTAL_PRICE
     *
     * @mbg.generated
     */
    public Integer getoTotalPrice() {
        return oTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_LIST.O_TOTAL_PRICE
     *
     * @param oTotalPrice the value for ORDER_LIST.O_TOTAL_PRICE
     *
     * @mbg.generated
     */
    public void setoTotalPrice(Integer oTotalPrice) {
        this.oTotalPrice = oTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_LIST.O_RETURN
     *
     * @return the value of ORDER_LIST.O_RETURN
     *
     * @mbg.generated
     */
    public Boolean getoReturn() {
        return oReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_LIST.O_RETURN
     *
     * @param oReturn the value for ORDER_LIST.O_RETURN
     *
     * @mbg.generated
     */
    public void setoReturn(Boolean oReturn) {
        this.oReturn = oReturn;
    }
}