package entity;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_ITEM.ORDER_I_ID
     *
     * @mbg.generated
     */
    private String orderIId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_ITEM.ORDER_ID
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_ITEM.PRODUCT_ID
     *
     * @mbg.generated
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_ITEM.OI_AMOUNT
     *
     * @mbg.generated
     */
    private Integer oiAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_ITEM.OI_PRICE
     *
     * @mbg.generated
     */
    private Boolean oiPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public OrderItem(String orderIId, String orderId, String productId, Integer oiAmount, Boolean oiPrice) {
        this.orderIId = orderIId;
        this.orderId = orderId;
        this.productId = productId;
        this.oiAmount = oiAmount;
        this.oiPrice = oiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM
     *
     * @mbg.generated
     */
    public OrderItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_ITEM.ORDER_I_ID
     *
     * @return the value of ORDER_ITEM.ORDER_I_ID
     *
     * @mbg.generated
     */
    public String getOrderIId() {
        return orderIId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_ITEM.ORDER_I_ID
     *
     * @param orderIId the value for ORDER_ITEM.ORDER_I_ID
     *
     * @mbg.generated
     */
    public void setOrderIId(String orderIId) {
        this.orderIId = orderIId == null ? null : orderIId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_ITEM.ORDER_ID
     *
     * @return the value of ORDER_ITEM.ORDER_ID
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_ITEM.ORDER_ID
     *
     * @param orderId the value for ORDER_ITEM.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_ITEM.PRODUCT_ID
     *
     * @return the value of ORDER_ITEM.PRODUCT_ID
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_ITEM.PRODUCT_ID
     *
     * @param productId the value for ORDER_ITEM.PRODUCT_ID
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_ITEM.OI_AMOUNT
     *
     * @return the value of ORDER_ITEM.OI_AMOUNT
     *
     * @mbg.generated
     */
    public Integer getOiAmount() {
        return oiAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_ITEM.OI_AMOUNT
     *
     * @param oiAmount the value for ORDER_ITEM.OI_AMOUNT
     *
     * @mbg.generated
     */
    public void setOiAmount(Integer oiAmount) {
        this.oiAmount = oiAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_ITEM.OI_PRICE
     *
     * @return the value of ORDER_ITEM.OI_PRICE
     *
     * @mbg.generated
     */
    public Boolean getOiPrice() {
        return oiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_ITEM.OI_PRICE
     *
     * @param oiPrice the value for ORDER_ITEM.OI_PRICE
     *
     * @mbg.generated
     */
    public void setOiPrice(Boolean oiPrice) {
        this.oiPrice = oiPrice;
    }
}