package entity;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCT_ID
     *
     * @mbg.generated
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CATEGORY_ID
     *
     * @mbg.generated
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.P_NAME
     *
     * @mbg.generated
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.P_DESC
     *
     * @mbg.generated
     */
    private String pDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.P_PRICE
     *
     * @mbg.generated
     */
    private Integer pPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated
     */
    public Product(String productId, String categoryId, String pName, String pDesc, Integer pPrice) {
        this.productId = productId;
        this.categoryId = categoryId;
        this.pName = pName;
        this.pDesc = pDesc;
        this.pPrice = pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated
     */
    public Product() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRODUCT_ID
     *
     * @return the value of PRODUCT.PRODUCT_ID
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRODUCT_ID
     *
     * @param productId the value for PRODUCT.PRODUCT_ID
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.CATEGORY_ID
     *
     * @return the value of PRODUCT.CATEGORY_ID
     *
     * @mbg.generated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.CATEGORY_ID
     *
     * @param categoryId the value for PRODUCT.CATEGORY_ID
     *
     * @mbg.generated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.P_NAME
     *
     * @return the value of PRODUCT.P_NAME
     *
     * @mbg.generated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.P_NAME
     *
     * @param pName the value for PRODUCT.P_NAME
     *
     * @mbg.generated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.P_DESC
     *
     * @return the value of PRODUCT.P_DESC
     *
     * @mbg.generated
     */
    public String getpDesc() {
        return pDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.P_DESC
     *
     * @param pDesc the value for PRODUCT.P_DESC
     *
     * @mbg.generated
     */
    public void setpDesc(String pDesc) {
        this.pDesc = pDesc == null ? null : pDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.P_PRICE
     *
     * @return the value of PRODUCT.P_PRICE
     *
     * @mbg.generated
     */
    public Integer getpPrice() {
        return pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.P_PRICE
     *
     * @param pPrice the value for PRODUCT.P_PRICE
     *
     * @mbg.generated
     */
    public void setpPrice(Integer pPrice) {
        this.pPrice = pPrice;
    }
}